CREATE TABLE scorecards (
  id INTEGER NOT NULL AUTO_INCREMENT,
  course_name VARCHAR(100),
  play_date VARCHAR(10),
  PRIMARY KEY (id)
);

CREATE TABLE yards (
  id INTEGER NOT NULL AUTO_INCREMENT,
  yard_1 INTEGER NOT NULL,
  yard_2 INTEGER NOT NULL,
  yard_3 INTEGER NOT NULL,
  yard_4 INTEGER NOT NULL,
  yard_5 INTEGER NOT NULL,
  yard_6 INTEGER NOT NULL,
  yard_7 INTEGER NOT NULL,
  yard_8 INTEGER NOT NULL,
  yard_9 INTEGER NOT NULL,
  yard_front INTEGER NOT NULL,
  yard_10 INTEGER NOT NULL,
  yard_11 INTEGER NOT NULL,
  yard_12 INTEGER NOT NULL,
  yard_13 INTEGER NOT NULL,
  yard_14 INTEGER NOT NULL,
  yard_15 INTEGER NOT NULL,
  yard_16 INTEGER NOT NULL,
  yard_17 INTEGER NOT NULL,
  yard_18 INTEGER NOT NULL,
  yard_back INTEGER NOT NULL,
  yard_total INTEGER NOT NULL,
  yard_handicap INTEGER NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (id) REFERENCES scorecards(id)
  ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE pars (
  id INTEGER NOT NULL AUTO_INCREMENT,
  pars_1 INTEGER NOT NULL,
  pars_2 INTEGER NOT NULL,
  pars_3 INTEGER NOT NULL,
  pars_4 INTEGER NOT NULL,
  pars_5 INTEGER NOT NULL,
  pars_6 INTEGER NOT NULL,
  pars_7 INTEGER NOT NULL,
  pars_8 INTEGER NOT NULL,
  pars_9 INTEGER NOT NULL,
  pars_front INTEGER NOT NULL,
  pars_10 INTEGER NOT NULL,
  pars_11 INTEGER NOT NULL,
  pars_12 INTEGER NOT NULL,
  pars_13 INTEGER NOT NULL,
  pars_14 INTEGER NOT NULL,
  pars_15 INTEGER NOT NULL,
  pars_16 INTEGER NOT NULL,
  pars_17 INTEGER NOT NULL,
  pars_18 INTEGER NOT NULL,
  pars_back INTEGER NOT NULL,
  pars_total INTEGER NOT NULL,
  pars_handicap INTEGER NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (id) REFERENCES scorecards(id)
  ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE player (
  id INTEGER NOT NULL AUTO_INCREMENT,
  name VARCHAR(50),
  score_1 INTEGER NOT NULL,
  score_2 INTEGER NOT NULL,
  score_3 INTEGER NOT NULL,
  score_4 INTEGER NOT NULL,
  score_5 INTEGER NOT NULL,
  score_6 INTEGER NOT NULL,
  score_7 INTEGER NOT NULL,
  score_8 INTEGER NOT NULL,
  score_9 INTEGER NOT NULL,
  score_front INTEGER NOT NULL,
  score_10 INTEGER NOT NULL,
  score_11 INTEGER NOT NULL,
  score_12 INTEGER NOT NULL,
  score_13 INTEGER NOT NULL,
  score_14 INTEGER NOT NULL,
  score_15 INTEGER NOT NULL,
  score_16 INTEGER NOT NULL,
  score_17 INTEGER NOT NULL,
  score_18 INTEGER NOT NULL,
  score_back INTEGER NOT NULL,
  score_total INTEGER NOT NULL,
  score_handicap INTEGER NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (id) REFERENCES scorecards (id)
  ON DELETE CASCADE ON UPDATE CASCADE
);